---
title: Blake Noll
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  redirects:
    title: Redirects
    output: true
email: nollblake@gmail.com
url: http://blakenoll.com
description: Full Stack Web Developer located in Los Angeles CA.
color:
  primary-dark: "#000000"
  links: "#219ab3"
footer: blakenoll.com
social:
- title: linkedin
  url: https://www.linkedin.com/in/blake-noll-73781297
- title: github
  url: https://github.com/blakenoll
markdown: kramdown
permalink: pretty
